export const HOST = "http://localhost:8080";

//VARIABLES DE SEGURIDAD
export const TOKEN_NAME='access_token';//VA ASI POR DEFECTO, ES EL NOMBRE DEL TOKEN EN EL JSON Q DEVUELVE EL BACK
export const CLIENT_ID='bibliotecadigitalfcf';//SE CORRESPONDE CON LO DEFINIDO EN EL PROPERTIES EN SPRING
export const CLIENT_SECRET='fcf2020';//SE CORRESPONDE CON LO DEFINIDO EN EL PROPERTIES EN SPRING